apiVersion: batch/v1
kind: CronJob
metadata:
  name: job1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job1
            image: alpine:3.16.2
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo hello from job1
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
          restartPolicy: OnFailure
